live_config_reload = true
import = ["~/.config/alacritty/rose-pine-moon.toml"]

[cursor.style]
blinking = "on"
shape = "beam"

[cursor]
thickness = 0.3

[colors]
transparent_background_colors = true
cursor = { text = "CellBackground", cursor = "CellForeground" }

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 6

[font.italic]
family = "MonoLisa"
style = "Italic"

[font.normal]
family = "MonoLisa"
style = "Medium"

[font.offset]
x = 0
y = 12

[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

[window]
decorations = "None"
dynamic_padding = false
opacity = 1

[window.padding]
x = 5
y = 2
