general.live_config_reload = true
general.import = ["~/.config/alacritty/rose-pine-moon.toml"]

[cursor]
thickness = 0.3
style = {shape="Beam", blinking="Always"}
vi_mode_style = {shape="Block", blinking="off"}

[colors]
transparent_background_colors = true
cursor = { text = "CellBackground", cursor = "CellForeground" }

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
size = 16.0

[font.bold]
family = "Maple Mono"
style = "Bold"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 6

[font.italic]
family = "Maple Mono"
style = "Medium Italic"

[font.normal]
family = "Maple Mono"
style = "Medium Regular"

[font.offset]
x = 0
y = 12

[[keyboard.bindings]]
chars = "\u000F"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\t"
key = "RBracket"
mods = "Command"

[window]
decorations = "None"
dynamic_padding = false
opacity = 1

[window.padding]
x = 5
y = 2
