#!/bin/sh
# yabairc file
# author: Bo Cao
# date: May 28, 2023
# --------------------

# Load yabai scripting additions
# sudo yabai --load-sa

# Restart yabai when dock restarts
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# General settings
GENERAL="auto_balance off
split_ratio 0.5
split_type auto
window_placement second_child"

# Layout settings
LAYOUT="layout bsp
bottom_padding 1
left_padding 1
right_padding 1
top_padding 1
window_gap 1"

# Mouse behavior settings
MOUSE="focus_follows_mouse off
mouse_action1 move
mouse_action2 resize
mouse_drop_action swap
mouse_follows_focus on
mouse_modifier fn"

# Enabled options
ENABLE_OPTS="$GENERAL
$LAYOUT
$MOUSE"

# Apply the enabled options
yabai -m config $ENABLE_OPTS

# Rules for unmanaged apps
# Softwares use floating window layout
UNMANAGED="System Settings
Activity Monitor
AdGuard
Alfred
App Store
AppCleaner
Archive Utility
Calculator
Dictionary
FaceTime
Hand Mirror
Input Source Pro
Keychain
Messages
Windows App
Music
Notifications
Numi
Preview
Python
Quantumult X
Screen Sharing
Screens
Sip
Software Update
System
System Information
VooV
WeCom
iStat Menus
zoom.us
wezterm-gui
mpv
Mac Mouse Fix
NetEaseMusic"

# Add rules for unmanaged apps
printf "%s\n" "$UNMANAGED" | xargs -P8 -I{} yabai -m rule --add "label=unmanage_{}" "app=^{}.*$" manage=off

# Exclude problematic apps from being managed
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add "label=Finder" "app=^Finder$" "title=(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add "label=Safari" "app=^Safari$" "title=^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add "label=About This Mac" "app=System Information" "title=About This Mac" manage=off
yabai -m rule --add "app=.*Booth$" manage=off
yabai -m rule --add "app=Mathematica" "title=Welcome to Wolfram Mathematica.*" manage=off
yabai -m rule --add "title=Preference.*" manage=off
yabai -m rule --add "title=Setting.*" manage=off
yabai -m rule --add "title=General.*" manage=off
yabai -m rule --add "title=^$" manage=off
yabai -m rule --add "app=WeChat" "title!=WeChat.*$" manage=off
yabai -m rule --add "app=Calender" "title= " manage=off
yabai -m rule --add "app=^Arc.*" "title=(Bo|General|Profiles|Shortcuts|Links|Advance)" manage=off
yabai -m rule --add "app=^Arc.*" "title=Little Arc.*" manage=off
yabai -m rule --apply
