#!/bin/sh
# yabairc file
# author: Bo Cao
# date: May 28, 2023
# --------------------


# Load yabai scripting additions
sudo yabai --load-sa

# Restart yabai when dock restarts
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# General settings
GENERAL="auto_balance off
split_ratio 0.50
split_type auto
window_placement second_child"

# Layout settings
LAYOUT="layout bsp
bottom_padding 2
left_padding 2
right_padding 2
top_padding 2
window_gap 2"

# Mouse behavior settings
MOUSE="focus_follows_mouse off
mouse_action1 move
mouse_action2 resize
mouse_drop_action swap
mouse_follows_focus on
mouse_modifier fn"

# Enabled options
ENABLE_OPTS="$GENERAL
$LAYOUT
$MOUSE"

# Apply the enabled options
yabai -m config $ENABLE_OPTS

# Rules for unmanaged apps
# Softwares use floating window layout
UNMANAGED="System Settings
System
Software Update
System Information
Activity Monitor
Preview
Alfred
App Store
Archive Utility
Keychain
Music
Messages
Calculator
Dictionary
FaceTime
Microsoft Remote Desktop
Python
Screen Sharing
Screens
zoom.us
iStat Menus
AppCleaner
Sip
Numi
Input Source Pro
AdGuard
WeCom
VooV
Quantumult X
Hand Mirror
Notifications"

# Add rule for all window layer
yabai -m rule --add app=".*" layer=normal

# Add rules for unmanaged apps
printf "%s\n" "$UNMANAGED" | while IFS= read -r app; do
    yabai -m rule --add "label=unmanage_$app" "app=^$app.*$" manage=off
done

# Exclude problematic apps from being managed
yabai -m rule --add "label=Finder" "app=^Finder$" "title=(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add "label=Safari" "app=^Safari$" "title=^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add "label=About This Mac" "app=System Information" "title=About This Mac" manage=off
yabai -m rule --add "label=Photo booth" "app=^Photo Booth$" manage=off
yabai -m rule --add "label=Photos" "app=Photos" manage=on
yabai -m rule --add "app=Mathematica" "title=Welcome to Wolfram Mathematica.*" manage=off
yabai -m rule --add "title=Preference.*" manage=off
yabai -m rule --add "title=Setting.*" manage=off
yabai -m rule --add "title=General.*" manage=off
yabai -m rule --add "title=^$" manage=off
yabai -m rule --add "app=WeChat" "title!=WeChat.*" manage=off
yabai -m rule --add "app=Calender" "title= " manage=off
yabai -m rule --add "app=wezterm-gui" manage=off layer=above
