#! /bin/dash
# =====================
# Ghostty config file
# ---------------------
# author: Bo Cao
# create date: Feb 10, 2025
# ---------------------
# version: 0.1
# =====================

# font settings
# ---------------------
font-family = "Maple Mono NF"
font-family = "LXGW WenKai Mono"
font-thicken = false
font-size = 16
font-synthetic-style = bold-italic
alpha-blending = linear-corrected

# line space settings
# ---------------------
adjust-cell-width = 2%
adjust-cell-height = 8%

# cursor settings
# ---------------------
cursor-invert-fg-bg = true
adjust-cursor-thickness = 2

# color settings
# ---------------------
theme = rose-pine
# theme = catppuccin-mocha
window-colorspace = display-p3
background-opacity = 0.95
palette = 2=#00ffaf

# window settings
# ---------------------
# macos-titlebar-style = tabs
window-decoration = false
window-padding-x = 8
window-padding-y = 2
window-padding-balance = true
macos-window-shadow = true

# system related settings
# ---------------------
mouse-hide-while-typing = true

clipboard-read = allow
clipboard-write = allow

quit-after-last-window-closed = true
shell-integration = zsh
macos-option-as-alt = left

image-storage-limit = 640000000

# keymaps
keybind = cmd+s=toggle_quick_terminal

# update settings
# ---------------------
auto-update = download
auto-update-channel = stable
