#! /bin/dash
# =====================
# Ghostty config file
# ---------------------
# author: Bo Cao
# create date: Feb 10, 2025
# ---------------------
# version: 0.1
# =====================

# font settings
# ---------------------
font-family = "Maple Mono NF"
font-family = "LXGW WenKai Mono"
font-thicken = false
font-size = 16
font-synthetic-style = bold-italic
alpha-blending = linear-corrected

# line space settings
# ---------------------
adjust-cell-width = 2%
adjust-cell-height = 8%

# cursor settings
# ---------------------
cursor-invert-fg-bg = true
adjust-cursor-thickness = 2

# color settings
# ---------------------
# theme = rose-pine
# theme = catppuccin-mocha
window-colorspace = display-p3
background-opacity = 0.95

# window settings
# ---------------------
macos-titlebar-style = hidden
window-padding-x = 8
window-padding-y = 2
window-padding-balance = true
macos-window-shadow = true

# system related settings
# ---------------------
mouse-hide-while-typing = true

clipboard-read = allow
clipboard-write = allow

quit-after-last-window-closed = true
shell-integration = zsh
macos-option-as-alt = left

image-storage-limit = 640000000

# keymaps
keybind = cmd+s=toggle_quick_terminal

# update settings
# ---------------------
auto-update = download
auto-update-channel = stable

# theme
background = #1e1e1f
foreground = #cbd5e1
palette = 8=#666666
palette = 12=#a8e0ff
palette = 14=#bafffe
palette = 10=#bdf8c7
palette = 13=#ebe5ff
palette = 9=#ffc4c4
palette = 15=#ffffff
palette = 11=#ffe8b9
palette = 0=#333333
palette = 4=#8fc7ff
palette = 6=#a1e8e5
palette = 2=#a4dfae
palette = 5=#d2ccff
palette = 1=#edabab
palette = 7=#f3f2f2
palette = 3=#eecfa0
cursor-color = #cbd5e1
selection-background = #cbd5e1
selection-foreground = #1e1e1f
