schemaVersion = 1

[catalogConfiguration]
customFolders = []
folderDepthOverrides = []

    [[catalogConfiguration.scriptsDirectories]]
    id = 'BB4DAEBE-57CA-479C-BB8B-39344A2C903C'
    path = '~/Documents/Software/dot_files/config/tuna/script'

[[catalogs.sortOrders]]
catalogIdentifier = 'Tuna.Internal.ClipboardProxyCatalog'
sortOrder = 'name.asc'

[[comboMode.bindings]]
key = 's'
url = 'tuna://run/path.%252FApplications%252FSafari.app/Open'

[[comboMode.bindings]]
key = 't'
url = 'tuna://run/path.%252FSystem%252FApplications%252FUtilities%252FTerminal.app/Open'

[[comboMode.bindings]]
key = 'f'
url = 'tuna://run/path.%252FSystem%252FLibrary%252FCoreServices%252FFinder.app/Open'

[[comboMode.bindings]]
key = 'm'
url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

[[comboMode.bindings]]
key = 'n'
url = 'tuna://run/path.%252FSystem%252FApplications%252FNotes.app/Open'

[[comboMode.bindings]]
key = 'd'
url = 'tuna://run/path.%252FUsers%252Fbo%252FDownloads/Open'

[[comboMode.bindings]]
key = 'h'
url = 'tuna://run/path.%252FUsers%252Fbo/Open'

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[hotkeys.app.comboMode]
carbonKeyCode = 0
carbonModifiers = 6912

[[hotkeys.custom]]
id = '104EF273-3466-4B05-97AC-7BCB2148D40A'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'TunaSystem.MenuItemsCatalog.Menu Items'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 12
    carbonModifiers = 4096

[[hotkeys.custom]]
id = '5E59F765-DD55-4967-8D37-7BE6EFBDC7F3'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'Tuna.Internal.ClipboardProxyCatalog.Clipboard History'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 41
    carbonModifiers = 4096

[[hotkeys.custom]]
id = '8AC78AA4-C6B5-4D02-B59A-95FC00DE6759'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = "TunaSmartLinks.SmartLinksActionsCatalog.Send to Smart Link\u2026"
    subjectIdentifier = 'Tuna.CurrentSelectionCatalog.Current Text Selection'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 17
    carbonModifiers = 4096

[settings]
backspaceBehavior = 'deleteCharacters'
comboModeKeyboardLayoutBehavior = 'forceUS'
comboModeModifierTrigger = 'rightCommand'
comboModeTriggerType = 'disabled'
resultListNavigationBindings = 'macOSStandard'
shelfAutoCloseWhenTasksComplete = true
showResultsImmediatelyOnActivation = true
spacebarBehavior = 'switchToTextMode'
talkModeTriggerType = 'disabled'
themeIdentifier = 'com.brnbw.tuna.themes.NormieBar'
typingTimeoutDuration = 2.5000000000000004

[[smartLinks.entries]]
enabled = true
name = 'bi'
requiresInput = true
template = 'https://search.bilibili.com/all?keyword={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'bing'
requiresInput = true
template = 'https://www.bing.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'bk'
requiresInput = true
template = 'https://baike.baidu.com/item/{{input}}'

[[smartLinks.entries]]
enabled = true
name = 'gg'
requiresInput = true
template = 'https://www.google.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'git'
requiresInput = true
template = 'https://github.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'gs'
requiresInput = true
template = 'https://scholar.google.com/scholar?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'sci'
requiresInput = true
template = 'https://www.scienceing.com/en/result?k={{input}}&s=1&searchType=en'

[[smartLinks.entries]]
enabled = true
name = 'st'
requiresInput = true
template = 'https://stackoverflow.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'wiki'
requiresInput = true
template = 'https://en.wikipedia.org/wiki/Special:Search?search={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'yt'
requiresInput = true
template = 'https://www.youtube.com/results?search_query={{input}}'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'system'