schemaVersion = 1

[actionPreferences]
objectOverrides = []
version = 2

    [[actionPreferences.typeRankings]]
    typeID = 'com.tuna.type.smart-folder'

        [[actionPreferences.typeRankings.actions]]
        actionKey = 'Browse'
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

        [[actionPreferences.typeRankings.actions]]
        actionKey = "Search for \u2026"
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

    [[actionPreferences.typeRankings]]
    typeID = 'com.tuna.type.text-snippet'

        [[actionPreferences.typeRankings.actions]]
        actionKey = 'Paste'
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

        [[actionPreferences.typeRankings.actions]]
        actionKey = 'Paste as Plain Text'
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

        [[actionPreferences.typeRankings.actions]]
        actionKey = 'Copy to Clipboard'
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

        [[actionPreferences.typeRankings.actions]]
        actionKey = 'Type Text'
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

        [[actionPreferences.typeRankings.actions]]
        actionKey = 'Define'
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

        [[actionPreferences.typeRankings.actions]]
        actionKey = 'Speak Text (Say)'
        catalogIdentifier = 'TunaCore.CommonActionsCatalog'

[catalogConfiguration]
customFolders = []
folderDepthOverrides = []

    [[catalogConfiguration.scriptsDirectories]]
    id = 'BB4DAEBE-57CA-479C-BB8B-39344A2C903C'
    path = '~/Documents/Software/dot_files/config/tuna/script'

[[catalogs.globalScopes]]
catalogIdentifier = 'Tuna.EffectsCatalog'
mode = 'some'
selectedItemKeys = [ 'Confetti', 'Math' ]

[[catalogs.globalScopes]]
catalogIdentifier = 'Tuna.ModesCatalog'
mode = 'some'
selectedItemKeys = [ 'Combo Mode', 'Fuzzy Mode', 'Text Mode' ]

[[catalogs.globalScopes]]
catalogIdentifier = 'TunaAutomation.ShortcutsCatalog'
mode = 'some'
selectedItemKeys = [ 'New Shortcut', 'Quit all apps' ]

[[catalogs.globalScopes]]
catalogIdentifier = 'TunaEmoji.EmojiCatalog'
mode = 'none'
selectedItemKeys = []

[[catalogs.sortOrders]]
catalogIdentifier = 'Tuna.Internal.ClipboardProxyCatalog'
sortOrder = 'capturedAt.desc'

[[comboMode.bindings]]
iconPath = 'link.badge.plus'
key = 's'

    [[comboMode.bindings.children]]
    key = 's'
    url = 'tuna://run/TunaSystem.MenuItemsCatalog.Menu%20Items/Tuna.BasicActionsCatalog.Browse'

    [[comboMode.bindings.children]]
    key = 'w'
    url = 'tuna://run/Tuna.CurrentSelectionCatalog.Current%20Clipboard/TunaCore.CommonActionsCatalog.Send%20to%20Script%E2%80%A6/TunaAutomation.ScriptsCatalog.Open%20links%20in%20Helium%20Work%20profile'

[[comboMode.bindings]]
iconPath = 'apple.terminal'
key = 'a'

    [[comboMode.bindings.children]]
    key = 'b'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.Helium/Open'

    [[comboMode.bindings.children]]
    key = 'm'
    url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

    [[comboMode.bindings.children]]
    key = 'f'
    url = 'tuna://run/path.%252FUsers%252Fbo/Open'

    [[comboMode.bindings.children]]
    key = 't'
    url = 'tuna://run/TunaCore.AllApplicationsCatalog.Ghostty/Open'

    [[comboMode.bindings.children]]
    key = 'n'
    url = 'tuna://run/path.%252FSystem%252FApplications%252FNotes.app/Open'

[hotkeys.app.activate]
carbonKeyCode = 49
carbonModifiers = 256

[hotkeys.app.comboMode]
carbonKeyCode = 0
carbonModifiers = 6912

[[hotkeys.custom]]
id = '08D2022A-D0F2-4DE4-8533-A9B9F0AEA140'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Toggle Shelf'
    subjectIdentifier = 'Tuna.Internal.ShelfCatalog.Shelf'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 1
    carbonModifiers = 4096

[[hotkeys.custom]]
id = '104EF273-3466-4B05-97AC-7BCB2148D40A'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'TunaSystem.MenuItemsCatalog.Menu Items'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 12
    carbonModifiers = 4096

[[hotkeys.custom]]
id = '5E59F765-DD55-4967-8D37-7BE6EFBDC7F3'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Browse'
    subjectIdentifier = 'Tuna.Internal.ClipboardProxyCatalog.Clipboard History'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 41
    carbonModifiers = 4096

[[hotkeys.custom]]
id = '760BB011-9707-4416-A7B0-755A591140EC'
presentation = 'hidden'

    [hotkeys.custom.command]
    actionIdentifier = 'Tuna.BasicActionsCatalog.Add to Shelf'
    subjectIdentifier = 'Tuna.CurrentSelectionCatalog.Current Selection'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 8
    carbonModifiers = 768

[[hotkeys.custom]]
id = '8AC78AA4-C6B5-4D02-B59A-95FC00DE6759'
presentation = 'auto'

    [hotkeys.custom.command]
    actionIdentifier = "TunaSmartLinks.SmartLinksActionsCatalog.Send to Smart Link\u2026"
    subjectIdentifier = 'Tuna.CurrentSelectionCatalog.Current Text Selection'

    [hotkeys.custom.shortcut]
    carbonKeyCode = 17
    carbonModifiers = 4096

[settings]
backspaceBehavior = 'deleteCharacters'
comboModeKeyboardLayoutBehavior = 'forceUS'
comboModeModifierTrigger = 'rightCommand'
comboModeTriggerType = 'modifier'
mainWindowAnimationsEnabled = false
resultListNavigationBindings = 'macOSStandard'
shelfAutoCloseWhenTasksComplete = true
showResultsImmediatelyOnActivation = true
talkModeTriggerType = 'disabled'
themeIdentifier = 'com.brnbw.tuna.themes.default'
typingTimeoutDuration = 2.5000000000000004

[[smartLinks.entries]]
enabled = true
name = 'bi'
requiresInput = true
template = 'https://search.bilibili.com/all?keyword={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'bing'
requiresInput = true
template = 'https://www.bing.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'bk'
requiresInput = true
template = 'https://baike.baidu.com/item/{{input}}'

[[smartLinks.entries]]
enabled = true
name = 'ca'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments%252FCalculation/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'con'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments%252FConference/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'db'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FApplications%252F%25E8%25B1%2586%25E5%258C%2585.app/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'do'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'dw'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDownloads/TunaCore.CommonActionsCatalog.Open/'

[[smartLinks.entries]]
enabled = true
name = 'gg'
requiresInput = true
template = 'https://www.google.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'git'
requiresInput = true
template = 'https://github.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'gs'
requiresInput = true
template = 'https://scholar.google.com/scholar?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'ji'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments%252FLab_activities%252Fjiqt/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'lab'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments%252FLab_activities%252Fjiqt/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'mn'
requiresInput = true
template = 'https://zh.moegirl.org.cn/index.php?search={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'nt'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments%252FNotes/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'pa'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments%252FPapers/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'pu'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252FDocuments%252FPublications/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'sci'
requiresInput = true
template = 'https://www.scienceing.com/en/result?k={{input}}&s=1&searchType=en'

[[smartLinks.entries]]
enabled = true
name = 'st'
requiresInput = true
template = 'https://stackoverflow.com/search?q={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'tmp'
requiresInput = false
template = 'tuna://run/path.%252FUsers%252Fbo%252Ftmp/TunaCore.CommonActionsCatalog.Open'

[[smartLinks.entries]]
enabled = true
name = 'wiki'
requiresInput = true
template = 'https://en.wikipedia.org/wiki/Special:Search?search={{input}}'

[[smartLinks.entries]]
enabled = true
name = 'yt'
requiresInput = true
template = 'https://www.youtube.com/results?search_query={{input}}'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.plugins.emoji'

    [catalogSettings.values]
    EmojiSkinTone = 'medium-light'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'system'